#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir "$install_dir/source"
if [[ $YNH_ARCH == "amd64" ]]
then
	ynh_setup_source --source_id="main" --dest_dir="$install_dir/source"
elif [[ $YNH_ARCH == "arm64" ]]
then
	ynh_setup_source --source_id="arm64" --dest_dir="$install_dir/source"
fi
#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="env" --destination="$install_dir/config/env"
ynh_config_add --template="ldap.toml" --destination="$install_dir/config/ldap.toml"
ynh_config_add --template="grafana.ini" --destination="$install_dir/config/grafana.ini"

mv "$install_dir/source/conf/provisioning" "$install_dir/config/"

mkdir -p "$data_dir/plugins"

myynh_set_permissions

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="An open source analytics and monitoring solution" --log="/var/log/$app/${app%_*}.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --action=start --wait_until="HTTP Server Listen" --log_path="/var/log/$app/${app%_*}.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
