#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status grafana-server >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove grafana-server
	yunohost service remove influxdb
fi

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# If NetData is installed, configure it not to feed InfluxDB any more
netdata_conf="/var/www/netdata/etc/netdata/exporting.conf"
if [[ -f "$netdata_conf" ]] ; then
    sed -i '/^\[exporting:global\]$/,/^\[/ {
        s/enabled = yes/enabled = no/
        s/update every = 60/# update every = 10/
      }' $netdata_conf
fi

ynh_safe_rm "/etc/grafana/grafana.ini"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
